### PR TITLE
Fix byd difficulty does not show

### PR DESCRIPTION
**Pull request by Haocen2004**

### CODE REVIEW

**Comment by Rosemoe** [comment]
This seems invalid because all BYD charts are collected from files/dl/ folder. The BYD charts can not be loaded from assets because they are not inside the APK.

**Comment by Haocen2004** [comment]
oops
I'm trying to apply it to fanmade pack and I forgot about this
sorry

**Comment by Rosemoe** [comment]
If you do need to attempt to load it, you can wrap the openStream call and some following statements to avoid exception when BYD chart does exists.

**Comment by Rosemoe** [comment]
Correction: you need to check if the file exists before creating a object of AssetsChartFile

**Comment by Haocen2004** [comment]
i have to go to sleep because my parents and I'll be doing more tests tomorrow morning.

**Comment by Rosemoe** [comment]
Ok. That's fine. Good night.

**Comment by Haocen2004** [comment]
The current version is able to read the chart files in the DL directory normally, just need to filter the byd difficulty so that it only reads from the dl directory
Tested on local device
```2022-03-26 08:14:40.693 2526-2526/? I/LSPosed-Bridge: add song:Infinity Heaven
2022-03-26 08:14:40.693 2526-2526/? I/LSPosed-Bridge: diff:0
2022-03-26 08:14:40.693 2526-2526/? I/LSPosed-Bridge: path:songs/infinityheaven/0.aff
2022-03-26 08:14:40.693 2526-2526/? I/LSPosed-Bridge: add song:Infinity Heaven
2022-03-26 08:14:40.693 2526-2526/? I/LSPosed-Bridge: diff:1
2022-03-26 08:14:40.693 2526-2526/? I/LSPosed-Bridge: path:songs/infinityheaven/1.aff
2022-03-26 08:14:40.693 2526-2526/? I/LSPosed-Bridge: add song:Infinity Heaven
2022-03-26 08:14:40.693 2526-2526/? I/LSPosed-Bridge: diff:2
2022-03-26 08:14:40.693 2526-2526/? I/LSPosed-Bridge: path:songs/infinityheaven/2.aff
2022-03-26 08:14:40.693 2526-2526/? I/LSPosed-Bridge: add song:Infinity Heaven
2022-03-26 08:14:40.693 2526-2526/? I/LSPosed-Bridge: diff:3
2022-03-26 08:14:40.693 2526-2526/? I/LSPosed-Bridge: path:songs/infinityheaven/3.aff
2022-03-26 08:14:40.693 2526-2526/? I/LSPosed-Bridge: add song:Infinity Heaven
2022-03-26 08:14:40.693 2526-2526/? I/LSPosed-Bridge: diff:3
2022-03-26 08:14:40.693 2526-2526/? I/LSPosed-Bridge: path:/data/user/0/moe.low.arc/files/dl/infinityheaven_3
```

**Comment by Rosemoe** [comment]
I think I'd change it by myself.

**Pull request merged**
